//
// Created by 陳其駿 on 5/19/18.
//

#ifndef CONCURRENT_TOOLKITS_CPP_CONFIG_H
#define CONCURRENT_TOOLKITS_CPP_CONFIG_H

#define THREAD_NUM      100
#define NODE_NUM        200

#endif //CONCURRENT_TOOLKITS_CPP_CONFIG_H
