//
// Created by 陳其駿 on 5/15/18.
//

#ifndef CONCURRENT_TOOLKITS_CPP_LAMPORT_BAKERY_TEST_H
#define CONCURRENT_TOOLKITS_CPP_LAMPORT_BAKERY_TEST_H

void lamport_bakery_test();


#endif //CONCURRENT_TOOLKITS_CPP_LAMPORT_BAKERY_TEST_H
